name: Publish VSIX
on:
  push:
    tags:
      - '*.*'

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Set up git repository
        uses: actions/checkout@v2
      - name: Install vsce
        run: npm install --location=global vsce
      - name: Install requirements
        run: npm install
      - name: Bundle extension
        run: npm run webpack
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{github.ref}}
          draft: true
          prerelease: false
      - name: Package extention
        run: vsce package --out package/term-poll_${{ github.ref }}.vsix
      - name: Upload released package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: $${{ steps.create_release.outputs.upload_url }}
          asset_path: out/term-poll_${{ github.ref }}.vsix
          asset_name: term-poll_${{ github.ref }}.vsix
          asset_content_type: vsix
